### ISSUE TITLE
allow awful.key in modalbind tables

### ISSUE THREAD

**Issue by crater2150** [crater2150/awesome-modalbind#1]
Currently, modalbind does not use awesome's `awful.key` structure for storing bindings. Allowing the use of it would make moving bindings from normal to modal easier and eventually also allow the use of modifiers.

**Comment by matsievskiysv** [comment]
Probably better to wait for the [new keygrabber api](https://awesomewm.org/apidoc/classes/awful.keygrabber.html) before implementing this.

**Comment by nimaipatel** [comment]
Would it be possible to add this now? I'd like to use modifiers in key-sequences too.

**Comment by crater2150** [comment]
I may have some time for it later this month. It looks like the new keygrabber API will make a lot of my code obsolete, it basically already does the majority of what I'm doing, with a similar syntax. I think modalbind will then only do the part with displaying a wibox with the current mode and keys

**Comment by crater2150** [comment]
Rewriting with the new keygrabber was a bit more work than anticipated, because nesting has to be handled differently and I tried to have most existing usages still work. The new implementation now supports modifier keys, by adding a modifier table before the key, just like in `awful.key`, e.g.:

```
{{"Mod4", "Shift"}, "x", function() print("mod4+shift+x pressed") end },
```
In contrast to `awful.key`, the modifier table can be left out if empty, so existing mappings should work without changes.
@nimaipatel you can try the new implementation in the [`new-keygrabber` branch](https://github.com/crater2150/awesome-modalbind/tree/new-keygrabber), until I have more time to test it and merge it into master.

**Comment by crater2150** [comment]
Tested it for some time, fixed a bug with separator lines. Now merged.
